# -- 顶部主导航 --
[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "标签"
  pageRef = "tags"
  weight = 20

[[main]]
  name = "分类"
  pageRef = "categories"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Hongwei6"
  weight = 100

# -- 底部页脚导航 --
[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "分类"
  pageRef = "categories"
  weight = 20
